default: dev

environments:
  local:
    database:
      host: localhost
      port: 5432
      user: ae_interview
      password: password
      dbname: analytics_db
      schema: raw

  dev:
    database:
      host: db
      port: 5432
      user: ae_interview
      password: password
      dbname: analytics_db
      schema: raw
